### ISSUE TITLE
Ask the user if he/she want to override the current clipboardand and not do it automatically.

### ISSUE THREAD

**Issue by JosteinFraNorge** [SchildCode/LowExCalc#1]

**Comment by SchildCode** [comment]
Can you explain the problem? For example, are you trying to copy the whole sheet input & output as a screen-dump in Word?

**Comment by JosteinFraNorge** [comment]
If you already have something stored on your clippbord it will get replaced by whatever your program provides. Thats why there should be a prompt and/or choice before you override the users clipboard.

**Comment by SchildCode** [comment]
This feature is by design. This act of clicking on the tab to draw the system acts as the "prompt".
